name: Parallel Scraper

on:
  push:
    branches:
      - tnbooks
  pull_request:
    branches:
      - tnbooks

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [1, 2, 3, 4, 5]  # 5 parallel jobs

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install || gem install mechanize

      - name: Run scraper chunk
        run: |
          START=$(( ( ${{ matrix.chunk }} - 1 ) * 400 + 1 ))
          END=$(( ${{ matrix.chunk }} * 400 ))
          ruby tnbooks.rb $START $END ${{ matrix.chunk }}


      - name: Upload chunk results
        uses: actions/upload-artifact@v4
        with:
          name: books-part-${{ matrix.chunk }}
          path: books_chunk_${{ matrix.chunk }}.json
