name: Parallel Scraper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [1]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install || gem install mechanize

      - name: Run scraper on part_${{ matrix.part }}
        run: |
          ruby culturel.rb list_part_${{ matrix.part }}.txt

      - name: Upload JSON results
        uses: actions/upload-artifact@v4
        with:
          name: books_part_${{ matrix.part }}
          path: books_part_${{ matrix.part }}.json
