name: Parallel Scraper

on:
  push:
    branches:
      - ceres
  pull_request:
    branches:
      - ceres

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: ["French", "Arabic", "English", "School Books", "Pedagogy"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          gem install mechanize nokogiri json csv

      - name: Run scraper for ${{ matrix.category }}
        run: ruby scrape.rb "${{ matrix.category }}"

      - name: Upload JSON result
        uses: actions/upload-artifact@v4
        with:
          name: books-json-${{ matrix.category }}
          path: output/${{ matrix.category }}.json

      - name: Upload CSV result
        uses: actions/upload-artifact@v4
        with:
          name: books-csv-${{ matrix.category }}
          path: output/${{ matrix.category }}.csv
